################################
#          BT Graves        #
#         by BT Pluginz       #
################################
#------------------------------
# Do not touch this value
# The Plugin updates the config file using it.
fileversion: 1
#------------------------------

# If the Plugin should check for new Versions
# default: true
checkVersion: true
# How long should graves last (in minutes)
# If you don't want to delete graves
# default: 60
graveTimeout: 60
# If the Armor stand should be small or not
# this changes the Hitbox of the Grave and
# the Height of the "Hologram" (Text)
# default: true
smallArmorStand: true
# How much % of the Players Experience should be saved
# 0 - 100
# default: 100
expPercentage: 100 # %

# by wolfino
messages:
  only-player: "&cSolo i player possono usare questo comando!"
  no-permission: "&cNon hai il permesso di usare questo comando!"
  no-graves-near: "&cNon ci sono graves vicinoa te"
  click: "&aClicca il bottone per ricevere gli item"